# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMainWindow, QWidget, QLabel, QPushButton, QLineEdit \
                            , QDateTimeEdit, QApplication

from PyQt5.QtCore import QRect, QDate, QTime
from PyQt5.QtGui import QFont, QIntValidator

import static.staticValues as staticValues

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.resize(773, 452)

        #메인 화면 색상py
        self.setStyleSheet("color: black;"
                        "background-color: white")

        font = QFont()
        font.setFamily("NanumGothic")
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(30, 20, 181, 51))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.edit_filePath = QLineEdit(self.centralwidget)
        self.edit_filePath.setGeometry(QRect(60, 80, 551, 21))
        self.edit_filePath.setInputMask("")
        self.edit_filePath.setReadOnly(True)
        self.edit_url = QLineEdit(self.centralwidget)
        self.edit_url.setGeometry(QRect(200, 130, 521, 21))
        self.edit_id = QLineEdit(self.centralwidget)
        self.edit_id.setGeometry(QRect(200, 170, 341, 21))
        self.edit_passwd = QLineEdit(self.centralwidget)
        self.edit_passwd.setGeometry(QRect(200, 210, 341, 21))
        self.button_file = QPushButton(self.centralwidget)
        self.button_file.setGeometry(QRect(630, 77, 93, 28))
        
        #버튼 스타일 변경
        self.button_file.setStyleSheet(staticValues.grayButtonStyleSheet)
        self.button_file.setFont(staticValues.buttonFont)

        font = QFont()
        font.setFamily("NanumGothic")
        self.button_file.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(60, 132, 100, 15))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(60, 172, 120, 15))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QRect(60, 212, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setGeometry(QRect(60, 270, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setGeometry(QRect(80, 312, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setGeometry(QRect(80, 352, 101, 16))
        font = QFont()
        font.setFamily("NanumGothic")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.dateTime_upload = QDateTimeEdit(self.centralwidget)
        self.dateTime_upload.setGeometry(QRect(180, 310, 194, 22))

        #오늘 날짜 세팅
        self.dateTime_upload.setDate(QDate.currentDate())
        self.dateTime_upload.setTime(QTime.currentTime())
        print(QTime.currentTime().addSecs(60))
        self.edit_period = QLineEdit(self.centralwidget)
        self.edit_period.setGeometry(QRect(180, 350, 113, 21))

        #가로/세로 입력창 숫자만 입력하도록 수정
        self.edit_period.setValidator(QIntValidator(1, 1440))

        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setGeometry(QRect(310, 353, 64, 15))
        self.button_write = QPushButton(self.centralwidget)
        self.button_write.setGeometry(QRect(180, 400, 391, 28))

        #버튼 스타일 변경
        self.button_write.setStyleSheet(staticValues.blueButtonStyleSheet)
        self.button_write.setFont(staticValues.buttonFont)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("MainWindow")
        self.label.setText("TISAUTORY")
        self.edit_filePath.setPlaceholderText("문단 파일 경로")
        self.button_file.setText("파일 열기")
        self.label_2.setText("URL")
        self.label_3.setText("ID")
        self.label_4.setText("PASSWORD")
        self.label_5.setText("게시 시간 설정")
        self.label_6.setText("게시 시작 날짜")
        self.label_7.setText("게시 주기")
        self.edit_period.setPlaceholderText("분단위 주기")
        self.label_8.setText("분")
        self.button_write.setText("자동 등록 시작")


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
